"""Category axioms for the calibration slice."""

from __future__ import annotations


def axiom(name: str) -> str:
    return name


class Lattices:
    class SubcategoryMethods:
        Nondegenerate = axiom("Nondegenerate")
        Integral = axiom("Integral")
        Even = axiom("Even")
        # S4: norm-based root-generated comment — contradicts reflective definition
        # even lattice generated by its roots {v : q(v) = +-2}
        RootGenerated = axiom("RootGenerated")
